/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author renan
 */
public class EscolherLogin extends javax.swing.JFrame {

    /**
     * Creates new form EscolherLogin
     */
    public EscolherLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginAdministrador = new javax.swing.JButton();
        btnLoginCliente = new javax.swing.JButton();
        btnLoginFuncionario = new javax.swing.JButton();
        btnLoginGerente = new javax.swing.JButton();
        lblEscolherLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoginAdministrador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLoginAdministrador.setText("Login Administrador");
        btnLoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdministradorActionPerformed(evt);
            }
        });

        btnLoginCliente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLoginCliente.setText("Login Cliente");

        btnLoginFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLoginFuncionario.setText("Login Funcionário");

        btnLoginGerente.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLoginGerente.setText("Login Gerente");

        lblEscolherLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEscolherLogin.setText("Fazer login em que tipo de conta?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoginAdministrador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoginCliente)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoginFuncionario)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoginGerente)
                        .addGap(46, 46, 46)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblEscolherLogin)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEscolherLogin)
                .addGap(33, 33, 33)
                .addComponent(btnLoginAdministrador)
                .addGap(18, 18, 18)
                .addComponent(btnLoginCliente)
                .addGap(18, 18, 18)
                .addComponent(btnLoginFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btnLoginGerente)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginAdministrador;
    private javax.swing.JButton btnLoginCliente;
    private javax.swing.JButton btnLoginFuncionario;
    private javax.swing.JButton btnLoginGerente;
    private javax.swing.JLabel lblEscolherLogin;
    // End of variables declaration//GEN-END:variables
}
