/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.saneamento_basico_r.model.view;

import com.mycompany.saneamento_basico_r.controller.ClienteController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author joserui
 */
public class FrAdministrador extends javax.swing.JDialog {

    ClienteController clienteController;
    Long idClienteEditando;

    public FrAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        clienteController = new ClienteController();

        initComponents();
        this.adicionarMascaraNosCampos();

        /*this.habilitarCampos(false);
        this.limparCampos();*/

        //edtListagem.setText(profController.imprimirListaProfessores());
        //clienteController.atualizarTabela(grdClientes);
    }

    /*public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panFormulario.getComponents().length; i++) {
            panFormulario.getComponent(i).setEnabled(flag);
        }
    }

    public void limparCampos() {
        edtNome.setText("");
        edtSexo.setText("");
        edtIdade.setText("");
        fEdtMatricula.setText("");
    }*/

    public void adicionarMascaraNosCampos() {
        try {
            // Precisa começar com uma letra, depois pode ser letra ou numero
            MaskFormatter maskUsuario = new MaskFormatter("?AAAAAAAAAAAAAAAAAAA");
            maskUsuario.install(fAdministradorUsuario);                                    
        } catch (ParseException ex) {
            Logger.getLogger(FrAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * O ideal seria entregar essa responsabiliadde para o controller para isso
     * deveriamos passar os componentes edt s
     *
     * OU senao criar um novo tipo representationModel, que será a representacao
     * do modelo na camada VIEW. Com isso criamos uma independencia da camada
     * MODEL.
     *
     * @param a
     */
    /*public void preencherFormulario(Cliente a) {
        edtNome.setText(a.getNome());
        edtSexo.setText(a.getSexo() + "");
        edtIdade.setText(a.getIdade() + "");
        fEdtMatricula.setText(a.getMatricula());
        edtAno.setText(a.getAnoIngresso() + "");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginAdministrador = new javax.swing.JLabel();
        lblAdministradorUsuario = new javax.swing.JLabel();
        fAdministradorUsuario = new javax.swing.JFormattedTextField();
        lblAdministradorSenha = new javax.swing.JLabel();
        fAdministradorSenha = new javax.swing.JFormattedTextField();
        btnUsuarioLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        lblLoginAdministrador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblLoginAdministrador.setText("Login Administrador");

        lblAdministradorUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAdministradorUsuario.setText("Usuário:");

        fAdministradorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAdministradorUsuarioActionPerformed(evt);
            }
        });

        lblAdministradorSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAdministradorSenha.setText("Senha:");

        fAdministradorSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAdministradorSenhaActionPerformed(evt);
            }
        });

        btnUsuarioLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnUsuarioLogin.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdministradorUsuario)
                    .addComponent(lblAdministradorSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnUsuarioLogin))
                    .addComponent(fAdministradorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fAdministradorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(lblLoginAdministrador)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLoginAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdministradorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fAdministradorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdministradorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fAdministradorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUsuarioLogin)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fAdministradorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAdministradorUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fAdministradorUsuarioActionPerformed

    private void fAdministradorSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAdministradorSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fAdministradorSenhaActionPerformed

    /**
     * Retorna o objeto (classe) da linha selecionada na grid.
     *
     * Uso a estratégia do metodo getValueAt() la na TableModel, receber coluna
     * -1 e retornar o objeto ao inves de uma célula.
     *
     * @return
     */
    /*private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdAlunos.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdAlunos.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuarioLogin;
    private javax.swing.JFormattedTextField fAdministradorSenha;
    private javax.swing.JFormattedTextField fAdministradorUsuario;
    private javax.swing.JLabel lblAdministradorSenha;
    private javax.swing.JLabel lblAdministradorUsuario;
    private javax.swing.JLabel lblLoginAdministrador;
    // End of variables declaration//GEN-END:variables
}
