/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.saneamento_basico_r.model.view.Gerente;

import com.mycompany.saneamento_basico_r.model.view.Adminisctrador.*;
import com.mycompany.saneamento_basico_r.model.view.Cliente.FrClienteHistoricoConsumo;
import com.mycompany.saneamento_basico_r.model.view.Cliente.FrClientePendencias;
import com.mycompany.saneamento_basico_r.controller.ClienteController;
import com.mycompany.saneamento_basico_r.model.view.CadastrarEmpresa.FrCadastroEmpresaSaneamento;
import com.mycompany.saneamento_basico_r.model.view.Planos.FrPlanosEscolher;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author joserui
 */
public class FrGerenteFuncoes extends javax.swing.JDialog {

    ClienteController clienteController;
    Long idClienteEditando;

    public FrGerenteFuncoes(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        
        clienteController = new ClienteController();

        initComponents();

        /*this.habilitarCampos(false);
        this.limparCampos();*/

        //edtListagem.setText(profController.imprimirListaProfessores());
        //clienteController.atualizarTabela(grdClientes);
    }

    /*public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panFormulario.getComponents().length; i++) {
            panFormulario.getComponent(i).setEnabled(flag);
        }
    }

    public void limparCampos() {
        edtNome.setText("");
        edtSexo.setText("");
        edtIdade.setText("");
        fEdtMatricula.setText("");
    }*/ 

    /**
     * O ideal seria entregar essa responsabiliadde para o controller para isso
     * deveriamos passar os componentes edt s
     *
     * OU senao criar um novo tipo representationModel, que será a representacao
     * do modelo na camada VIEW. Com isso criamos uma independencia da camada
     * MODEL.
     *
     * @param a
     */
    /*public void preencherFormulario(Cliente a) {
        edtNome.setText(a.getNome());
        edtSexo.setText(a.getSexo() + "");
        edtIdade.setText(a.getIdade() + "");
        fEdtMatricula.setText(a.getMatricula());
        edtAno.setText(a.getAnoIngresso() + "");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGerente = new javax.swing.JLabel();
        btnCadastrarRede = new javax.swing.JButton();
        btnAdicionarPlanos = new javax.swing.JButton();
        btnSuporte = new javax.swing.JButton();
        btnManutencao = new javax.swing.JButton();
        btnGeraRelatorioDeConsumo = new javax.swing.JButton();
        btnbtnGeraRelatorioDeFatura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        lblGerente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblGerente.setText("Funções Gerente");

        btnCadastrarRede.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastrarRede.setText("Cadastrar Rede de Saneamento");
        btnCadastrarRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarRedeActionPerformed(evt);
            }
        });

        btnAdicionarPlanos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAdicionarPlanos.setText("Adicionar Planos");
        btnAdicionarPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlanosActionPerformed(evt);
            }
        });

        btnSuporte.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSuporte.setText("Suporte Tecnico");
        btnSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporteActionPerformed(evt);
            }
        });

        btnManutencao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnManutencao.setText("Manutenção do Sistema");
        btnManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManutencaoActionPerformed(evt);
            }
        });

        btnGeraRelatorioDeConsumo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGeraRelatorioDeConsumo.setText("Gerar Relatório de Consumo");
        btnGeraRelatorioDeConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraRelatorioDeConsumoActionPerformed(evt);
            }
        });

        btnbtnGeraRelatorioDeFatura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnbtnGeraRelatorioDeFatura.setText("Gerar Relatório de Faturas");
        btnbtnGeraRelatorioDeFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnGeraRelatorioDeFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGeraRelatorioDeConsumo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnbtnGeraRelatorioDeFatura)))
                .addGap(0, 206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGerente)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnManutencao)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrarRede)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdicionarPlanos)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSuporte)
                        .addGap(261, 261, 261))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManutencao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarRede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarPlanos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeraRelatorioDeConsumo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbtnGeraRelatorioDeFatura)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarRedeActionPerformed
        FrCadastroEmpresaSaneamento dlgEmpresaSaneamento = new FrCadastroEmpresaSaneamento(this, true);

        dlgEmpresaSaneamento.setLocationRelativeTo(this);
        dlgEmpresaSaneamento.setVisible(true);
    }//GEN-LAST:event_btnCadastrarRedeActionPerformed

    private void btnAdicionarPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarPlanosActionPerformed

    private void btnSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporteActionPerformed

    }//GEN-LAST:event_btnSuporteActionPerformed

    private void btnManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManutencaoActionPerformed
        FrAdministradorAvisoManutencao dlgAvisoManutencao = new FrAdministradorAvisoManutencao(this, true);

        dlgAvisoManutencao.setLocationRelativeTo(this);
        dlgAvisoManutencao.setVisible(true);
    }//GEN-LAST:event_btnManutencaoActionPerformed

    private void btnGeraRelatorioDeConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraRelatorioDeConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGeraRelatorioDeConsumoActionPerformed

    private void btnbtnGeraRelatorioDeFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnGeraRelatorioDeFaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbtnGeraRelatorioDeFaturaActionPerformed

    /**
     * Retorna o objeto (classe) da linha selecionada na grid.
     *
     * Uso a estratégia do metodo getValueAt() la na TableModel, receber coluna
     * -1 e retornar o objeto ao inves de uma célula.
     *
     * @return
     */
    /*private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdAlunos.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdAlunos.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlanos;
    private javax.swing.JButton btnCadastrarRede;
    private javax.swing.JButton btnGeraRelatorioDeConsumo;
    private javax.swing.JButton btnManutencao;
    private javax.swing.JButton btnSuporte;
    private javax.swing.JButton btnbtnGeraRelatorioDeFatura;
    private javax.swing.JLabel lblGerente;
    // End of variables declaration//GEN-END:variables
}
