/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.saneamento_basico_r.model.view.Cliente;

import com.mycompany.saneamento_basico_r.model.view.Cliente.FrClienteCadastroResidencia;
import com.mycompany.saneamento_basico_r.controller.ClienteController;
import com.mycompany.saneamento_basico_r.model.view.RecuperarSenha.FrRecuperarSenha;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author joserui
 */
public class FrCliente extends javax.swing.JDialog {

    ClienteController clienteController;
    Long idClienteEditando;

    public FrCliente(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        
        clienteController = new ClienteController();

        initComponents();
        this.adicionarMascaraNosCampos();

        /*this.habilitarCampos(false);
        this.limparCampos();*/

        //edtListagem.setText(profController.imprimirListaProfessores());
        //clienteController.atualizarTabela(grdClientes);
    }

    /*public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panFormulario.getComponents().length; i++) {
            panFormulario.getComponent(i).setEnabled(flag);
        }
    }

    public void limparCampos() {
        edtNome.setText("");
        edtSexo.setText("");
        edtIdade.setText("");
        fEdtMatricula.setText("");
    }*/ 

    public void adicionarMascaraNosCampos() {
        try {
            // Precisa começar com uma letra, depois pode ser letra ou numero
            MaskFormatter maskUsuario = new MaskFormatter("?AAAAAAAAAAAAAAAAAAA");
            maskUsuario.install(fClienteUsuario);                                    
        } catch (ParseException ex) {
            Logger.getLogger(FrCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * O ideal seria entregar essa responsabiliadde para o controller para isso
     * deveriamos passar os componentes edt s
     *
     * OU senao criar um novo tipo representationModel, que será a representacao
     * do modelo na camada VIEW. Com isso criamos uma independencia da camada
     * MODEL.
     *
     * @param a
     */
    /*public void preencherFormulario(Cliente a) {
        edtNome.setText(a.getNome());
        edtSexo.setText(a.getSexo() + "");
        edtIdade.setText(a.getIdade() + "");
        fEdtMatricula.setText(a.getMatricula());
        edtAno.setText(a.getAnoIngresso() + "");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginCliente = new javax.swing.JLabel();
        lblClienteUsuario = new javax.swing.JLabel();
        fClienteUsuario = new javax.swing.JFormattedTextField();
        lblClienteSenha = new javax.swing.JLabel();
        fClienteSenha = new javax.swing.JFormattedTextField();
        btnUsuarioLogin = new javax.swing.JButton();
        lblClienteRegistrar = new javax.swing.JLabel();
        btnUsuarioRegistrar = new javax.swing.JButton();
        btnSenhaEsqueci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        lblLoginCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblLoginCliente.setText("Login Cliente");

        lblClienteUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblClienteUsuario.setText("Usuário:");

        fClienteUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fClienteUsuarioActionPerformed(evt);
            }
        });

        lblClienteSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblClienteSenha.setText("Senha:");

        fClienteSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fClienteSenhaActionPerformed(evt);
            }
        });

        btnUsuarioLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnUsuarioLogin.setText("Login");
        btnUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioLoginActionPerformed(evt);
            }
        });

        lblClienteRegistrar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblClienteRegistrar.setText("Não tem uma conta? Faça seu registro clicando no botão:");

        btnUsuarioRegistrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnUsuarioRegistrar.setText("Registrar");
        btnUsuarioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioRegistrarActionPerformed(evt);
            }
        });

        btnSenhaEsqueci.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnSenhaEsqueci.setText("Esqueci a senha");
        btnSenhaEsqueci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaEsqueciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClienteUsuario)
                    .addComponent(lblClienteSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnUsuarioLogin))
                    .addComponent(fClienteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSenhaEsqueci)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLoginCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblClienteRegistrar)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUsuarioRegistrar)
                        .addGap(306, 306, 306))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLoginCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fClienteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSenhaEsqueci))
                .addGap(18, 18, 18)
                .addComponent(btnUsuarioLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblClienteRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarioRegistrar)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioRegistrarActionPerformed
        FrClienteCadastroResidencia dlgRegistrarCliente = new FrClienteCadastroResidencia(this, true);
        
        dlgRegistrarCliente.setLocationRelativeTo(this);
        dlgRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_btnUsuarioRegistrarActionPerformed

    private void fClienteUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fClienteUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fClienteUsuarioActionPerformed

    private void fClienteSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fClienteSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fClienteSenhaActionPerformed

    private void btnUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioLoginActionPerformed
        this.dispose();
        FrClienteFuncoes dlgFuncoesCliente = new FrClienteFuncoes(this, true);
        
        dlgFuncoesCliente.setLocationRelativeTo(this);
        dlgFuncoesCliente.setVisible(true);
    }//GEN-LAST:event_btnUsuarioLoginActionPerformed

    private void btnSenhaEsqueciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaEsqueciActionPerformed
        FrRecuperarSenha dlgRecuperarSenha = new FrRecuperarSenha(this, true);
        
        dlgRecuperarSenha.setLocationRelativeTo(this);
        dlgRecuperarSenha.setVisible(true);
    }//GEN-LAST:event_btnSenhaEsqueciActionPerformed

    /**
     * Retorna o objeto (classe) da linha selecionada na grid.
     *
     * Uso a estratégia do metodo getValueAt() la na TableModel, receber coluna
     * -1 e retornar o objeto ao inves de uma célula.
     *
     * @return
     */
    /*private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdAlunos.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdAlunos.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSenhaEsqueci;
    private javax.swing.JButton btnUsuarioLogin;
    private javax.swing.JButton btnUsuarioRegistrar;
    private javax.swing.JFormattedTextField fClienteSenha;
    private javax.swing.JFormattedTextField fClienteUsuario;
    private javax.swing.JLabel lblClienteRegistrar;
    private javax.swing.JLabel lblClienteSenha;
    private javax.swing.JLabel lblClienteUsuario;
    private javax.swing.JLabel lblLoginCliente;
    // End of variables declaration//GEN-END:variables
}
