/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.saneamento_basico_r.model.view.Cliente;

import com.mycompany.saneamento_basico_r.model.view.Cliente.FrClientePendencias;
import com.mycompany.saneamento_basico_r.controller.ClienteController;
import com.mycompany.saneamento_basico_r.model.view.Planos.FrPlanoConfirmacaoCancelamento;
import com.mycompany.saneamento_basico_r.model.view.Planos.FrPlanosEscolher;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author joserui
 */
public class FrClienteFuncoes extends javax.swing.JDialog {

    ClienteController clienteController;
    Long idClienteEditando;

    public FrClienteFuncoes(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        
        clienteController = new ClienteController();

        initComponents();

        /*this.habilitarCampos(false);
        this.limparCampos();*/

        //edtListagem.setText(profController.imprimirListaProfessores());
        //clienteController.atualizarTabela(grdClientes);
    }

    /*public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panFormulario.getComponents().length; i++) {
            panFormulario.getComponent(i).setEnabled(flag);
        }
    }

    public void limparCampos() {
        edtNome.setText("");
        edtSexo.setText("");
        edtIdade.setText("");
        fEdtMatricula.setText("");
    }*/ 

    /**
     * O ideal seria entregar essa responsabiliadde para o controller para isso
     * deveriamos passar os componentes edt s
     *
     * OU senao criar um novo tipo representationModel, que será a representacao
     * do modelo na camada VIEW. Com isso criamos uma independencia da camada
     * MODEL.
     *
     * @param a
     */
    /*public void preencherFormulario(Cliente a) {
        edtNome.setText(a.getNome());
        edtSexo.setText(a.getSexo() + "");
        edtIdade.setText(a.getIdade() + "");
        fEdtMatricula.setText(a.getMatricula());
        edtAno.setText(a.getAnoIngresso() + "");
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistoricoConsumo = new javax.swing.JButton();
        btnSelecionarNovoPlano = new javax.swing.JButton();
        lblLoginCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPlanos = new javax.swing.JLabel();
        btnCancelarPlano = new javax.swing.JButton();
        btnPagarPendencias = new javax.swing.JButton();
        btnPagarPendencias1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        btnHistoricoConsumo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnHistoricoConsumo.setText("Visualizar Histórico de Consumo");
        btnHistoricoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoConsumoActionPerformed(evt);
            }
        });

        btnSelecionarNovoPlano.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSelecionarNovoPlano.setText("Selecionar um novo Plano");
        btnSelecionarNovoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarNovoPlanoActionPerformed(evt);
            }
        });

        lblLoginCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblLoginCliente.setText("Funções Cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblPlanos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPlanos.setText("Planos Ativos");

        btnCancelarPlano.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCancelarPlano.setText("Cancelar Plano Selecionado");
        btnCancelarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPlanoActionPerformed(evt);
            }
        });

        btnPagarPendencias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPagarPendencias.setText("Pagar Pendências");
        btnPagarPendencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPendenciasActionPerformed(evt);
            }
        });

        btnPagarPendencias1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPagarPendencias1.setText("Requisitar Suporte");
        btnPagarPendencias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPendencias1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(lblLoginCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnSelecionarNovoPlano))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnHistoricoConsumo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPagarPendencias1)
                            .addComponent(btnPagarPendencias))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPlanos)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelarPlano)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLoginCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPlanos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarPlano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHistoricoConsumo)
                        .addGap(34, 34, 34)
                        .addComponent(btnSelecionarNovoPlano)
                        .addGap(33, 33, 33)
                        .addComponent(btnPagarPendencias)
                        .addGap(31, 31, 31)
                        .addComponent(btnPagarPendencias1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoricoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoConsumoActionPerformed
        FrClienteHistoricoConsumo dlgHistoricoCliente = new FrClienteHistoricoConsumo(this, true);
        
        dlgHistoricoCliente.setLocationRelativeTo(this);
        dlgHistoricoCliente.setVisible(true);
    }//GEN-LAST:event_btnHistoricoConsumoActionPerformed

    private void btnSelecionarNovoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarNovoPlanoActionPerformed
        FrPlanosEscolher dlgPlanosCliente = new FrPlanosEscolher(this, true);
        
        dlgPlanosCliente.setLocationRelativeTo(this);
        dlgPlanosCliente.setVisible(true);
    }//GEN-LAST:event_btnSelecionarNovoPlanoActionPerformed

    private void btnCancelarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPlanoActionPerformed
        FrPlanoConfirmacaoCancelamento dlgCancelarPlano = new FrPlanoConfirmacaoCancelamento(this, true);
        
        dlgCancelarPlano.setLocationRelativeTo(this);
        dlgCancelarPlano.setVisible(true);
    }//GEN-LAST:event_btnCancelarPlanoActionPerformed

    private void btnPagarPendenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPendenciasActionPerformed
        FrClientePendencias dlgPendenciasCliente = new FrClientePendencias(this, true);
        
        dlgPendenciasCliente.setLocationRelativeTo(this);
        dlgPendenciasCliente.setVisible(true);
    }//GEN-LAST:event_btnPagarPendenciasActionPerformed

    private void btnPagarPendencias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPendencias1ActionPerformed
        FrClienteSuporteRequisicao dlgSuporte = new FrClienteSuporteRequisicao(this, true);
        
        dlgSuporte.setLocationRelativeTo(this);
        dlgSuporte.setVisible(true);
    }//GEN-LAST:event_btnPagarPendencias1ActionPerformed

    /**
     * Retorna o objeto (classe) da linha selecionada na grid.
     *
     * Uso a estratégia do metodo getValueAt() la na TableModel, receber coluna
     * -1 e retornar o objeto ao inves de uma célula.
     *
     * @return
     */
    /*private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdAlunos.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdAlunos.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPlano;
    private javax.swing.JButton btnHistoricoConsumo;
    private javax.swing.JButton btnPagarPendencias;
    private javax.swing.JButton btnPagarPendencias1;
    private javax.swing.JButton btnSelecionarNovoPlano;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblLoginCliente;
    private javax.swing.JLabel lblPlanos;
    // End of variables declaration//GEN-END:variables
}
